### ISSUE TITLE
Problem Firmware Update

### ISSUE THREAD

**Issue by JanHH2019** [makerbase-mks/MKS-Robin2#8]
I have a mks robin2 v1.0 and wanted to install the latest firmware V1.0.3. Unfortunately that doesn't work, he loads the firmware, transfers the font and PIC files and then says "complete".
When I turn the board off and on again, the message booting comes up and nothing happens.
Have already tried the older versions of firmware V1.0.1 and V1.0.2, all with the same result.
What can I do now?

**Comment by makerbase-mks** [comment]
Can you provide your Robin2 firmware updating process?

**Comment by JanHH2019** [comment]
This version i have use first time ::

[https://github.com/makerbase-mks/MKS-Robin/blob/master/MKS%20Robin2/Mks_Robin2_V1.0.3%20Release%20file.rar](url)

I also tried these two versions ::

[https://github.com/makerbase-mks/MKS-Robin/blob/master/MKS%20Robin2/History%20version/Mks_Robin2_V1.0.2%20Release%20file.rar](url)

[https://github.com/makerbase-mks/MKS-Robin/blob/master/MKS%20Robin2/History%20version/Mks_Robin2_V1.0.2%20Release%20file.rar](url)

![2020-09-22 07 45 54](https://user-images.githubusercontent.com/48419827/93847894-90119c80-fca8-11ea-999c-7175567aed01.jpg)
![2020-09-22 07 46 08](https://user-images.githubusercontent.com/48419827/93847899-9142c980-fca8-11ea-8c80-8acbea712362.jpg)
![2020-09-22 07 45 07](https://user-images.githubusercontent.com/48419827/93847902-91db6000-fca8-11ea-81e0-159d0613fdec.jpg)
![2020-09-22 07 45 11](https://user-images.githubusercontent.com/48419827/93847907-9273f680-fca8-11ea-9cb9-5ebff5622efe.jpg)
![2020-09-22 07 45 15](https://user-images.githubusercontent.com/48419827/93847910-93a52380-fca8-11ea-95a0-1c5bd0cbb30a.jpg)
![2020-09-22 07 45 31](https://user-images.githubusercontent.com/48419827/93847913-943dba00-fca8-11ea-8b08-d6f73382233f.jpg)
![2020-09-22 07 45 49](https://user-images.githubusercontent.com/48419827/93847915-94d65080-fca8-11ea-891a-493b0111d9f8.jpg)

this is what the content of the sd card looks like after trying to boot ::
![nachboot](https://user-images.githubusercontent.com/48419827/93847970-bafbf080-fca8-11ea-878e-c0067726d23b.jpg)

**Comment by JanHH2019** [comment]
The problem is solved. I also wrote to Makerbase in the Facebook chat and got the tip there to format another SD card or to format the SD card. I have now done that and then the update runs through, it now also shows that it is reading in the PIC's and the fonts again and then the board starts correctly. Thank you for the effort..
